<?php

/**
 * @file
 * Contains minimal_share.module.
 */

use \Drupal\Core\Entity\EntityInterface;
use \Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_theme().
 */
function minimal_share_theme() {
  return [
    'minimal_share' => [
      'variables' => [
        'providers' => NULL,
      ],
    ],
    'minimal_share_item' => [
      'variables' => [
        'title' => NULL,
        'attributes' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_entity_extra_field_info().
 */
function minimal_share_entity_extra_field_info() {
  $extra = [];
  /** @var \Drupal\minimal_share\MinimalShareManager $manager */
  $manager = \Drupal::service('minimal_share.manager');
  $config = $manager->getConfig();

  // Iterate all enabled entity types and provide
  // an extra field for each bundle.
  foreach ($config['entity_types'] as $entity_type) {
    /** @var \Drupal\Core\Entity\EntityTypeBundleInfoInterface $definition */
    $bundle_info = \Drupal::service('entity_type.bundle.info');
    $bundles = $bundle_info->getBundleInfo($entity_type);

    foreach ($bundles as $bundle => $info) {
      $extra[$entity_type][$bundle]['display']['minimal_share'] = [
        'label' => t('Minimal Share'),
        'description' => t('Minimal share buttons'),
        'visible' => FALSE,
      ];
    }
  }

  return $extra;
}

/**
 * Implements hook_entity_view().
 */
function minimal_share_entity_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display, $view_mode) {
  /** @var \Drupal\minimal_share\MinimalShareManager $manager */
  $manager = \Drupal::service('minimal_share.manager');
  $entity_type = $entity->getEntityTypeId();

  // Make sure entity type has been enabled and component has been added
  // on "Manage display" page.
  if ($manager->entityTypeEnabled($entity_type) && $display->getComponent('minimal_share')) {
    $share_info = $manager->buildShareInfo($entity);

    $build['minimal_share'] = $manager->build($share_info);
  }
}

/**
 * Implements template_preprocess_HOOK().
 */
function template_preprocess_minimal_share_item(&$variables) {
  $variables['label'] = $variables['title'];
}
